# CONFIGURACIÓN ACTUALIZADA CHAMPIONS LEAGUE PREDICTOR
# Football-Data.org API

API_FOOTBALL_KEY = "fd9ecc768e3644dfa9b30e9536031700"

API_FOOTBALL_BASE_URL = "https://api.football-data.org/v4"

HEADERS = {
    'X-Auth-Token': API_FOOTBALL_KEY
}

DATA_DIR = "../data"